---
name: "distill"
output_dir: "_site"
title: ""
navbar:
  right:
    - text: "Riders"
      href: https://www.procyclingstats.com/race/tour-de-france/2026/startlist
    - text: "Route"
      href: https://www.letour.fr/en/overall-route
  left:
    - text: "Results"
      href: 
      menu:
        - text: "Stage 1"
          href: stage-1_Daily_Report.html
        - text: "Stage 2"
          href: stage-2_Daily_Report.html
        - text: "Stage 3"
          href: stage-3_Daily_Report.html
        - text: "Stage 4"
          href: stage-4_Daily_Report.html
   
    - text: "Standings"
      href:
      menu:
        - text: "Overall Standings"  
          href: Current_overall.html
        - text: "Points Standings"  
          href: Current_points.html
    - text: "Teams"
      href: Teams.html
    - text: "Rules"
      href: rules.html
          
    - icon: logo.png
      href: https://github.com/rstudio/distill
      
output:
distill::distill_article:
  css: styles.css

---
